### ISSUE TITLE
main class 

### ISSUE THREAD

**Issue by zzgulu** [anuzzolese/csv2rdf#2]
Hi, 

After a successful build and running the jar file I am getting below error. Any hint? Thanks!
Appreciate the script & help! 

zzgulu@ubuntu:~/csv2rdf-master/target$ java -jar stlab.csv2rdf-1.0.jar 
Error: Could not find or load main class it.cnr.istc.stlab.csv2rdf.cmd.Main

**Comment by anuzzolese** [comment]
Dear @zzgulu,

the bug should have been fixed with the latest commit.
Check if it works for you case.

Cheers,
Andrea

**Comment by zzgulu** [comment]
Thank you very much ! It's working now, however, script only accepts -n -o -s options. I can not assign a mapping file (-m) or format (-f)

**Comment by anuzzolese** [comment]
I am using it with -m and -f options.
I am not able to reproduce the issue.
Can you provide further information?

**Comment by zzgulu** [comment]
I am running the script with these options and getting the message below. Screenshot is attached as well
<img width="1054" alt="screen shot 2018-02-13 at 10 52 24 am" src="https://user-images.githubusercontent.com/21363767/36159247-41d4d77a-10ac-11e8-9c5c-0d238139e11c.png">
 

java -jar stlab.csv2rdf.jar -s '\t' -m mapping.txt -o musician.ttl test.csv 
usage: csv2rdf
 -n,--namespace <uri>    Namespace for resources.
 -o,--output <file>      RDF output file.
 -s,--separator <char>   Separator character.

<img width="674" alt="screen shot 2018-02-13 at 10 56 23 am" src="https://user-images.githubusercontent.com/21363767/36159393-93fea256-10ac-11e8-8a63-dbd26c36b518.png">

**Comment by anuzzolese** [comment]
I see.
Since you compile binaries from source code you should run the app form csv2rdf-master/target/stlab.csv2rdf-1.0.jar.
The JAR in bin is not updated when you compile with Maven.

**Comment by zzgulu** [comment]
Thanks for the prompt reply ! 
This time I ran it from the target directory but got a different error. I am using the attached file from your sample example. If you think compilation is still the issue, would it be possible to download a pre-compiled version? Appreciate it !
[mapping.txt](https://github.com/anuzzolese/csv2rdf/files/1720919/mapping.txt)
[musician.txt](https://github.com/anuzzolese/csv2rdf/files/1720920/musician.txt)



<img width="1112" alt="screen shot 2018-02-13 at 12 23 48 pm" src="https://user-images.githubusercontent.com/21363767/36163932-d80e7faa-10b8-11e8-9c85-6123ede83fe4.png">

**Comment by anuzzolese** [comment]
OK, I think it is fixed now.

**Comment by zzgulu** [comment]
Thanks! Seems working now, converting a very large csv file (80Mb) to ttl
